$(function(){
	var inputRrror=1;
	$("#username").blur(function(){
		if($(this).val().length<6||$(this).val().length>12){
			$(".Hint_1").text("用户名必须在6-12位！");
			inputRrror=1
		}else{
			$(".Hint_1").text("");
			inputRrror=0
		}
	})
	$("#passwordone").blur(function(){
		if($(this).val().length<6||$(this).val().length>12){
			$(".Hint_2").text("密码必须在6-12位！")
			inputRrror=1
		}else{
			$(".Hint_2").text("")
			inputRrror=0
		}
	})
	$("#password").blur(function(){
		if($("#passwordone").val()!=$(this).val()){
			$(".Hint_3").text("密码和重复密码不一致！")
			inputRrror=1
		}else{
			$(".Hint_3").text("")
			inputRrror=0
		}
	})
	$("#usertel").blur(function(){
		if($(this).val()==""){
			$(".Hint_3").text("手机号不能为空！")
			inputRrror=1
		}else{
			$(".Hint_3").text("")
			inputRrror=0
		}
	})
	$("#reg").click(function(){
		if(inputRrror==1){
			AlertMsg("信息输入有误！")
		}else{
			$.ajax({
				type:"post",
				url:url+"reg",
				async:true,
				data:{
					username:$("#username").val(),
					userpwd:$("#password").val(),
				    usertel:$("#usertel").val()
				},
				success:function(data){
					if(data.errcode==0){
						location.href="login.html"
					}else{
						AlertMsg(data.msg)
					}
				}
			});
		}
		
	})
	function AlertMsg(y){
		$('.alert').fadeIn()
		$('.alert').text(y)
		setTimeout(function(){
			$('.alert').fadeOut()
		},3000)
	}
})